
name: 'video_games'
version: '1.0.0'
config-version: 2
profile: my-bigquery-db
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target" 
clean-targets:         
  - "target"
  - "dbt_packages"
models:
  video_games:
    materialized: table